export const seedProducts = [
  {
    title: "Premium Orthopedic Memory Foam Dog Bed",
    description: "Provide your furry friend with ultimate comfort. This orthopedic memory foam dog bed relieves joint pain, improves mobility, and features a washable, waterproof cover.",
    price: 89.99,
    category: "Dogs",
    categorySlug: "dog-essentials",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1541781774459-bb2af2892614?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_bed",
    features: ["Therapeutic memory foam", "Waterproof inner liner", "Machine washable plush cover"],
    pros: ["Excellent for older dogs with arthritis", "Easy to clean", "Non-slip bottom"],
    cons: ["May take 24 hours to fully expand", "Slight foam odor initially"],
    isHotDeal: true
  },
  {
    title: "Smart Automatic Pet Feeder with HD Camera",
    description: "Never miss a meal! This Wi-Fi enabled automatic feeder lets you schedule portions, monitor your pet via a 1080p camera, and even talk to them using 2-way audio.",
    price: 129.99,
    category: "Smart Pet Tech",
    categorySlug: "pet-tech",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1623387641177-e8a49a74a49c?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_feeder",
    features: ["1080p HD Camera with Night Vision", "Smartphone App Control", "2-Way Audio Communication"],
    pros: ["Reliable portion control", "Great peace of mind while away", "Keeps food fresh"],
    cons: ["Requires 2.4GHz Wi-Fi network", "App setup can take a few minutes"],
    isHotDeal: false
  },
  {
    title: "Multi-Level Cat Tree Tower with Scratching Posts",
    description: "The ultimate playground for your cats. Features multiple cozy perches, sisal-wrapped scratching posts, and interactive dangling toys to keep your felines entertained for hours.",
    price: 119.50,
    category: "Cats",
    categorySlug: "cat-trees",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542194605-728b704c35e9?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_cattree",
    features: ["Multiple resting platforms", "Natural sisal scratching posts", "Sturdy base to prevent tipping"],
    pros: ["Perfect for multiple cats", "Saves furniture from scratches", "Soft plush fabric"],
    cons: ["Requires assembly", "Takes up significant floor space"],
    isHotDeal: true
  },
  {
    title: "Interactive Laser Toy for Cats & Dogs",
    description: "Keep your pets active and entertained! This automatic rotating laser toy features multiple speed settings and unpredictable patterns to stimulate their hunting instincts.",
    price: 34.99,
    category: "Toys",
    categorySlug: "interactive-toys",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_laser",
    features: ["3 speed modes (Slow, Fast, Random)", "Automatic shut-off after 15 mins", "Quiet motor operation"],
    pros: ["Great exercise for indoor pets", "Hands-free entertainment", "Long battery life"],
    cons: ["Some pets may figure out the pattern", "Does not work well on very thick rugs"],
    isHotDeal: false
  },
  {
    title: "Heavy-Duty No Pull Dog Harness",
    description: "A comfortable, breathable, and highly durable harness designed to stop pulling safely. Features a front clip for training and a back clip for relaxed walking, plus reflective strips for night safety.",
    price: 29.99,
    category: "Accessories",
    categorySlug: "dog-accessories",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1601758066233-2dc5877f6b98?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_harness",
    features: ["Front and back D-rings", "Breathable air mesh padding", "Reflective safety stitching"],
    pros: ["Instantly reduces pulling", "Easy to put on and take off", "Highly visible at night"],
    cons: ["Sizing can be tricky for deep-chested breeds", "Requires initial adjustment"],
    isHotDeal: false
  },
  {
    title: "Self-Cleaning Automatic Cat Litter Box",
    description: "Say goodbye to scooping! This advanced self-cleaning litter box automatically removes waste, controls odors with UV light and carbon filters, and tracks your cat's health via an app.",
    price: 499.00,
    category: "Cats",
    categorySlug: "litter-boxes",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1629898083897-393c0bc5fbc9?auto=format&fit=crop&w=600&q=80",
    affiliateUrl: "https://amzn.to/example_litter",
    features: ["Automatic waste sifting", "Odor control technology", "Health monitoring app integration"],
    pros: ["Saves time and hassle", "Excellent odor control", "Whisper-quiet operation"],
    cons: ["High initial investment", "Takes up more space than traditional boxes"],
    isHotDeal: true
  }
];
